### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by kh0w** [RatWasHere/Studio-Bot-Maker#1]
**What is your bug?**
Unable to install, it says i already have it open (which i dont)
It might be because i have almost no space on my C:/ drive, which it would be nice to add an option to choose a path to install
**How could I reproduce your bug?**
1. Download
2. Try to install

**What did you expect was going to happen?**
it shouldve installed

**Screenshots - Errors - Anything helps!**
![image](https://github.com/RatWasHere/Studio-Bot-Maker/assets/123299631/b8b85b67-8428-4f1a-a96e-8e91ccafc9df)
![image](https://github.com/RatWasHere/Studio-Bot-Maker/assets/123299631/6b9cd72f-cf53-4cd0-a4d5-3b23b268597e)

**Desktop (please complete the following information):**
 -  Latest release (2.5.2)

**Additional context**
It might be because my C:/ drive is full, then it would be nice to have a path option

**Comment by kh0w** [comment]
nevermind, stopped being an idiot and cleared some space. would be nice to add a path choosing option though!

**Comment by RatWasHere** [comment]
Pfft, yeah will soon enough add the way to choose the installation path. You can use junctions until then! Will resolve the issue when I modify the installer location. 💗 Working on a fix immediately

**Comment by RatWasHere** [comment]
Would be nice if electron builder wasn't such a pain; Sorry for the delay of release, still not out yet, but in my defense SBM V3 has gotten real big changes 😂

**Comment by RatWasHere** [comment]
Sorry for the wait - I've managed release V3 with this patch; 
[Live in V3](https://github.com/RatWasHere/Studio-Bot-Maker/releases/tag/v3.0.0) (be aware it's a beta!)

Don't forget to join the [Support Guild](https://discord.gg/wjXz7jGgCw) on discord <3
