### ISSUE TITLE
2 suggestions

### ISSUE THREAD

**Issue by FleeksLoft** [RatWasHere/Studio-Bot-Maker#6]
It would be nice to have these 2 things 

    Link commands as well as being able to use variables from another group to another. 2nd suggestion: Action to config Boolean

**Comment by RatWasHere** [comment]
i dont undertand wtf you mean

here's something that might help you word stuff better: https://www.cambridgeenglish.org/images/starters-word-list-picture-book.pdf

until then, you can count these as nonexistent. 


cheers, rat

**Comment by RatWasHere** [comment]
Oh followup to the first suggestion

already possible


cheers, rat

**Comment by FleeksLoft** [comment]
> i dont undertand wtf you mean
> 
> here's something that might help you word stuff better: https://www.cambridgeenglish.org/images/starters-word-list-picture-book.pdf
> 
> until then, you can count these as nonexistent.
> 
> cheers, rat

An action to do the booleans for Parameter and stuff you know! To do the ephemeral enabled if boolean true

**Comment by RatWasHere** [comment]
We've already got a "Compare" action.

I don't see the need for something else

**Comment by RatWasHere** [comment]
This seems not to be an issue, therefore case closed. Your feedback will be taken in consideration 👯 

Until then, have fun 🧇
