### ISSUE TITLE
Module Error Bug!

### ISSUE THREAD

**Issue by FleeksLoft** [RatWasHere/Studio-Bot-Maker#7]
![wa](https://github.com/RatWasHere/Studio-Bot-Maker/assets/122408285/319b61e9-a582-4a4b-8577-9e25ebbc758a)
When trying to run bot file, it says "module named oceanic.js not found. Require stack" It happens in host and sbm runner

**Comment by RatWasHere** [comment]
This was fixed in v3.4; Case closed 🔨 🔨
